[global]
    #version = "0.0.1"
    ifname = "wan0"
    workers = 10
[log]
    path = "/opt/forwardcloud/log"
[mode]
    debug = true
[cloud]
    interval = 1
    count = 1
    workers = 10
    url = "http://34.29.138.72"
[sql]
    # host = "test.example.com"
    # port = 1337
    # user = "tset"
    # password = "test"
    # dbname = "test"
[zeek]
    bin = "/opt/zeek/bin/zeekctl"
    [[zeek.type]]
        name = "type1"
        path = "/opt/zeek/share/zeek/site"
        dir = "site"
    [[zeek.type]]
        name = "type2"
        path = "/opt/zeek/share/zeek/Zeek-Intelligence-Feeds"
        dir = "Zeek-Intelligence-Feeds"
    [[zeek.type]]
        name = "type3"
        path = "/etc/suricata/rules"
        dir = "rules"
    [zeek.event]
        routing_key = "zeek"
        [[zeek.event.file]]
        name = "alert_detail"
        path = "/opt/zeek/logs/current/alert.log"

        [[zeek.event.file]]
        name = "suricata_detail"
        path = "/var/log/suricata/eve_alert.json"

        [[zeek.event.file]]
        name = "conn_detail"
        path = "/opt/zeek/logs/current/conn.log"

        [[zeek.event.file]]
        name = "dns_detail"
        path = "/opt/zeek/logs/current/dns.log"

        [[zeek.event.file]]
        name = "files_detail"
        path = "/opt/zeek/logs/current/files.log"

        [[zeek.event.file]]
        name = "http_detail"
        path = "/opt/zeek/logs/current/http.log"

        [[zeek.event.file]]
        name = "ntp_detail"
        path = "/opt/zeek/logs/current/ntp.log"

        [[zeek.event.file]]
        name = "ssl_detail"
        path = "/opt/zeek/logs/current/ssl.log"

        [[zeek.event.file]]
        name = "weird_detail"
        path = "/opt/zeek/logs/current/weird.log"

    [[zeek.file]]
    	project =  "invalid"
		routing_key = "block_info"
		name = "invalid_detail"
		path = "/var/log/nftables/drop.log"
		format = "regex_invalid"
		# regex = "?"
[mqtt]
    url = "wss://app.cyfoundry.com/mqtt"
    username = "user"
    password = "citadel@1qaz@WSX3edc"

[updater]
    apiURL  =         "http://34.29.138.72/api/edge/files/"
	binURL  =         "http://34.29.138.72/api/edge/files/"
	diffURL =         "http://34.29.138.72/api/edge/files/"
	dir     =         "ck"

[patch]
    diffURL =         "http://34.29.138.72/api/edge/updateFile"
    dir     =         "/tmp"
